# 2. Merging DataFrames

This part discusses the basic and essential practical steps for integrating data from various sources.

Dealing with data from different sources requires essentially the integration between these sources to have a full information view. For example, if you collect data about house pricing separately in each suburb, you might need to "concatenate" data together to get a view of the house prices all over Victoria and even Australia. However, each data collection might have different attributes. How to merge them together to get a complete yet precise (with no duplication) presentation of the whole collection? Consider another example for sales department, when you have customer details in one table and product details in another table. How can we use Python (pandas library) to execute the join between the two DataFrame and manage the many to many relationship. This is exactly about implementing database techniques for merging tables using python on a general data.

Panda library has offered methods to manage the data integration task. In the following, we will discuss each method with examples.

There are four ways to merge/combine between different DataFrames in pandas:
- concatenating,
- appending,
- merging, and
- joining.

Each has its own use cases and best practice. We present concatenating and appending in this tutorial, the other two methods will be discussed in the next tutorial (week 11B). In all of these methods, we assume data is fetched or scrapped from the web (as explained in week 10) or it is stored locally on the machine. We also assume that the data from each source is stored in a DataFrame structure. We start first with the easiest way for merging DataFrame with concatenating.

In [14]:
import pandas as pd

## 2.1 Concatenating
This refers to gluing together data from different DataFrames by stacking them either vertically or side by side. Consider the following example.

In [15]:
# create three example dataframes to store the data
example_df1 = pd.DataFrame({'Student_ID': ['1', '2', '3', '4'],
                      'First_Name': ['A1','A2','A3','A4'],
                    'Last_Name': ['B1', 'B2', 'B3', 'B4']},
                  index=[1,2,3,4])
example_df2 = pd.DataFrame({'Student_ID': ['4', '5', '6', '7','8'],
                      'First_Name': ['A4','A5','A6','A7','A8'],
                    'Last_Name': ['B4', 'B5', 'B6', 'B7','b8']},
                 index= [4,5,6,7,8])
example_df3 = pd.DataFrame({'Student_ID': ['9', '10', '11', '12'],
                    'Last_Name': ['B9', 'B10', 'B11', 'B12'],
                  'address':['AD9','AD10','AD11','AD12']})

In [16]:
example_df1

  Student_ID First_Name Last_Name
1          1         A1        B1
2          2         A2        B2
3          3         A3        B3
4          4         A4        B4

In [17]:
example_df2

  Student_ID First_Name Last_Name
4          4         A4        B4
5          5         A5        B5
6          6         A6        B6
7          7         A7        B7
8          8         A8        b8

In [18]:
example_df3

  Student_ID Last_Name address
0          9        B9     AD9
1         10       B10    AD10
2         11       B11    AD11
3         12       B12    AD12

Now we have three DataFrames, df1, df2, and df3. We want to concatenate them together. The following code demonstrates how to concatenate them vertically.

Along the `row axis`, the number of columns should be the same. The same applies to the column axis when concatenating horizontally.

In [19]:
concat_1_2_row = pd.concat([example_df1,example_df2])
concat_1_2_row

  Student_ID First_Name Last_Name
1          1         A1        B1
2          2         A2        B2
3          3         A3        B3
4          4         A4        B4
4          4         A4        B4
5          5         A5        B5
6          6         A6        B6
7          7         A7        B7
8          8         A8        b8

If we want to concatenate them horizontally, we can set the `axis` parameter to 1.

In [20]:
concat_1_2_column = pd.concat([example_df1,example_df2], axis=1)
concat_1_2_column

  Student_ID First_Name Last_Name Student_ID First_Name Last_Name
1          1         A1        B1        NaN        NaN       NaN
2          2         A2        B2        NaN        NaN       NaN
3          3         A3        B3        NaN        NaN       NaN
4          4         A4        B4          4         A4        B4
5        NaN        NaN       NaN          5         A5        B5
6        NaN        NaN       NaN          6         A6        B6
7        NaN        NaN       NaN          7         A7        B7
8        NaN        NaN       NaN          8         A8        b8

How about concatenating all the three DataFrames together? The following code demonstrates how to concatenate them together.

`pd.concat([df1, df2, df3])` where the `df1`, `df2`, and `df3` are the DataFrames to be concatenated. If you have more than three DataFrames, you can add them to the list. For example, `pd.concat([df1, df2, df3, ... ,dfn])`.

In [21]:
concat_1_2_3_all = pd.concat([example_df1,example_df2,example_df3])
concat_1_2_3_all

  Student_ID First_Name Last_Name address
1          1         A1        B1     NaN
2          2         A2        B2     NaN
3          3         A3        B3     NaN
4          4         A4        B4     NaN
4          4         A4        B4     NaN
5          5         A5        B5     NaN
6          6         A6        B6     NaN
7          7         A7        B7     NaN
8          8         A8        b8     NaN
0          9        NaN        B9     AD9
1         10        NaN       B10    AD10
2         11        NaN       B11    AD11
3         12        NaN       B12    AD12

As explained in this example, concatenation glues different DataFrames together without considering the index of any or duplication that might cause. When concatenating, you need to make sure that all DataFrames have the same headers. Otherwise, the values of any column that does not exist in the union of headers of concatenated DataFrame will be replaced with NAN values, as shown when concatenated `example_df3` with `example_df1` and `example_df2`.

Note also, concatenation assigns the default index when the index was not provided in the original DataFrame (as in `example_df3`).  
`ignore_index` method is used in case you want to concatenate the DataFrames and ignore the indexes (because they are not meaningful)

In [22]:
concat_1_3_ignore_index = pd.concat([example_df1, example_df3], ignore_index=True)
print(example_df1)
print(example_df3)
print(concat_1_3_ignore_index)

  Student_ID First_Name Last_Name
1          1         A1        B1
2          2         A2        B2
3          3         A3        B3
4          4         A4        B4
  Student_ID Last_Name address
0          9        B9     AD9
1         10       B10    AD10
2         11       B11    AD11
3         12       B12    AD12
  Student_ID First_Name Last_Name address
0          1         A1        B1     NaN
1          2         A2        B2     NaN
2          3         A3        B3     NaN
3          4         A4        B4     NaN
4          9        NaN        B9     AD9
5         10        NaN       B10    AD10
6         11        NaN       B11    AD11
7         12        NaN       B12    AD12

The concatenation is very useful when you have data (with the same attributes) coming from different sources i.e., house prices collected from each suburb. So we glue them together to get a view for house prices all over victoria. We can also add another key column to indicate the source of each chunk of data in a hierarchical way. The example below explains this as follows:

In [23]:
concat_1_2_with_keys = pd.concat([example_df1,example_df2], keys=['source1','source2'])
print(concat_1_2_with_keys)

          Student_ID First_Name Last_Name
source1 1          1         A1        B1
        2          2         A2        B2
        3          3         A3        B3
        4          4         A4        B4
source2 4          4         A4        B4
        5          5         A5        B5
        6          6         A6        B6
        7          7         A7        B7
        8          8         A8        b8

An important use case for concatenating is when different perspectives of the same data are collected, so we need to concatenate all the information together to get all the details in one DataFrame. The following example illustrates the concatenation of DataFrame represents landlord profile with another DataFrame for the property details. The concatenation in this case has to be implemented along the horizontal axis (`axis=1`) rather than the vertical one, while the default concatenation axis is 0 (vertical).

In [24]:
example_df4 = pd.DataFrame({'Student_ID': ['1', '2', '3', '4'],
                      'Addres': ['AD1','AD2','AD3','AD4'],
                    'year': ['Y1', 'Y2', 'Y3', 'Y4']},
                 index=(1,2,3,4)
                 )

In [25]:
concat_1_4_horizontal = pd.concat([example_df1, example_df4],axis=1)
concat_1_4_horizontal

  Student_ID First_Name Last_Name Student_ID Addres year
1          1         A1        B1          1    AD1   Y1
2          2         A2        B2          2    AD2   Y2
3          3         A3        B3          3    AD3   Y3
4          4         A4        B4          4    AD4   Y4

In [26]:
concat_2_4_horizontal = pd.concat([example_df2, example_df4],axis=1)
concat_2_4_horizontal

  Student_ID First_Name Last_Name Student_ID Addres year
4          4         A4        B4          4    AD4   Y4
5          5         A5        B5        NaN    NaN  NaN
6          6         A6        B6        NaN    NaN  NaN
7          7         A7        B7        NaN    NaN  NaN
8          8         A8        b8        NaN    NaN  NaN
1        NaN        NaN       NaN          1    AD1   Y1
2        NaN        NaN       NaN          2    AD2   Y2
3        NaN        NaN       NaN          3    AD3   Y3

In [27]:
example_df2.index

Index([4, 5, 6, 7, 8], dtype='int64')

Concatenating `example_df2` and `example_df4` results in many NAN values because of the non-overlapping in index. Therefore, joining the DataFrames is very useful in this case. Concatenation gives you the three options to handle the other axes too (apart from the one we concatenate on) using outer or inner options or using a specific index. The outer option is the default gets the union of data and grantees zero loss. The previous example shows the outer join of `example_df2` and `example_df4`.  On the other hand, inner gets the intersection between the two DataFrames. Last but not least, the “join_axes” argument is used for joining with a specific index.

In [28]:
joint_2_4 = pd.concat([example_df2, example_df4],axis=1,join= 'outer')
print(example_df2)
print(example_df4)
print(joint_2_4)

  Student_ID First_Name Last_Name
4          4         A4        B4
5          5         A5        B5
6          6         A6        B6
7          7         A7        B7
8          8         A8        b8
  Student_ID Addres year
1          1    AD1   Y1
2          2    AD2   Y2
3          3    AD3   Y3
4          4    AD4   Y4
  Student_ID First_Name Last_Name Student_ID Addres year
4          4         A4        B4          4    AD4   Y4
5          5         A5        B5        NaN    NaN  NaN
6          6         A6        B6        NaN    NaN  NaN
7          7         A7        B7        NaN    NaN  NaN
8          8         A8        b8        NaN    NaN  NaN
1        NaN        NaN       NaN          1    AD1   Y1
2        NaN        NaN       NaN          2    AD2   Y2
3        NaN        NaN       NaN          3    AD3   Y3

## 2.2 Append
Append method in Series and DataFrames is a shortcut of concatenating. It is easy to use but not efficient in terms of performance. When appending a DataFrame, the original DataFrame remains in memory and a new appended one is created. In the appending process, the indexes must be disjoint but the columns do not need to be.

In [29]:
#dataframe.append has been deprecated in recent version of panadas, but you can still use '_append()' or concat() instead
appended_df= example_df1._append([example_df2, example_df3])
appended_df

  Student_ID First_Name Last_Name address
1          1         A1        B1     NaN
2          2         A2        B2     NaN
3          3         A3        B3     NaN
4          4         A4        B4     NaN
4          4         A4        B4     NaN
5          5         A5        B5     NaN
6          6         A6        B6     NaN
7          7         A7        B7     NaN
8          8         A8        b8     NaN
0          9        NaN        B9     AD9
1         10        NaN       B10    AD10
2         11        NaN       B11    AD11
3         12        NaN       B12    AD12

You can mix/concatenate both Series and DataFrames. Concat (and therefore append) makes a full copy of the data, and that constantly reusing this function can create a significant performance hit. In the following section, we will introduce merge and join as a more efficient way for merging DataFrames in Tutorial 6.


## 2.3 Simple Merge

Concat and append have limited capabilities in joining tables through keys and considering the inter-relationship between tables. Merge and join on the other hand combine DataFrames based on a key. According to concepts of relational databases like SQL, there are three types of relationships between tables:

1.	**One-to-one:** When each primary key value relates to only one (or no) record in the related table.

2.	**One-to-many:** When the primary key table contains only one record that relates to none, one, or many records in the related table.

3.	**Many-to-many:** When each record in both tables can relate to any number of records (or no records) in the other table.

We will discuss in the following how merge manages the three types of relationships. The following is an example of using merge for one-to-many relationship between table respresnts customer details and shopping history for each customer.

In [30]:
customers_df = pd.DataFrame({'Customer_ID': ['1', '2', '3', '4'],
                      'First_Name': ['A1','A2','A3','A4'],
                    'Last_Name': ['B1', 'B2', 'B3', 'B4']})
shopping_history_df = pd.DataFrame({'Customer_ID': ['1', '1', '1', '4','5'],
                            'Product_ID':['100','200','300','400','500'],
                      'product': ['Oil','Sugar','Tea','Milk','Eggs']})
merged_df = pd.merge(shopping_history_df, customers_df)
print(customers_df)
print(shopping_history_df)
print(merged_df)

  Customer_ID First_Name Last_Name
0           1         A1        B1
1           2         A2        B2
2           3         A3        B3
3           4         A4        B4
  Customer_ID Product_ID product
0           1        100     Oil
1           1        200   Sugar
2           1        300     Tea
3           4        400    Milk
4           5        500    Eggs
  Customer_ID Product_ID product First_Name Last_Name
0           1        100     Oil         A1        B1
1           1        200   Sugar         A1        B1
2           1        300     Tea         A1        B1
3           4        400    Milk         A4        B4

Try to change `Customer_ID` to another name.

In [31]:
try:
    merged_df_new = pd.merge(customers_df, shopping_history_df, on="Product_ID")
    merged_df_new
except KeyError as e:
    print("KeyError:", e)

KeyError: 'Product_ID'

Now the KeyError is raised because the key is not found in the DataFrame. To avoid this error, we can use the `on` parameter to specify the key to merge on. The following code demonstrates how to merge the two DataFrames using the `on` parameter.

In [32]:
customers_df2 = pd.DataFrame({'CID': ['1', '2', '3', '4'],
                      'First_Name': ['A1','A2','A3','A4'],
                    'Last_Name': ['B1', 'B2', 'B3', 'B4']})
customers_df2

  CID First_Name Last_Name
0   1         A1        B1
1   2         A2        B2
2   3         A3        B3
3   4         A4        B4

In [33]:
merged_on_key = pd.merge(customers_df2, shopping_history_df,left_on='CID',right_on='Customer_ID')
print (customers_df2)
print (shopping_history_df)
print (merged_on_key)

  CID First_Name Last_Name
0   1         A1        B1
1   2         A2        B2
2   3         A3        B3
3   4         A4        B4
  Customer_ID Product_ID product
0           1        100     Oil
1           1        200   Sugar
2           1        300     Tea
3           4        400    Milk
4           5        500    Eggs
  CID First_Name Last_Name Customer_ID Product_ID product
0   1         A1        B1           1        100     Oil
1   1         A1        B1           1        200   Sugar
2   1         A1        B1           1        300     Tea
3   4         A4        B4           4        400    Milk

`Note`: The default `how` setting for merge is `inner`


In the joined table, some records are deleted because they do not have a corresponding record in the original DataFrame (such as customer 2,3,5 and Eggs). This happens because the deafult method for merging is the inner join. For zero information loss, you can use outer join instead. The outer join could be full outer (getting full information from both DataFrames), left (only from the left DataFrame) or right (using left, right methods).

In [34]:
print (customers_df)
print (shopping_history_df)
merged_outer= pd.merge(customers_df, shopping_history_df, how='outer')
print (merged_outer)
merged_left= pd.merge(customers_df,shopping_history_df, how='left')
print (merged_left)
merged_right= pd.merge(shopping_history_df, customers_df,how='right')
print (merged_right)

  Customer_ID First_Name Last_Name
0           1         A1        B1
1           2         A2        B2
2           3         A3        B3
3           4         A4        B4
  Customer_ID Product_ID product
0           1        100     Oil
1           1        200   Sugar
2           1        300     Tea
3           4        400    Milk
4           5        500    Eggs
  Customer_ID First_Name Last_Name Product_ID product
0           1         A1        B1        100     Oil
1           1         A1        B1        200   Sugar
2           1         A1        B1        300     Tea
3           2         A2        B2        NaN     NaN
4           3         A3        B3        NaN     NaN
5           4         A4        B4        400    Milk
6           5        NaN       NaN        500    Eggs
  Customer_ID First_Name Last_Name Product_ID product
0           1         A1        B1        100     Oil
1           1         A1        B1        200   Sugar
2           1         A1        B1        300     Tea
3           2         A2        B2        NaN     NaN
4           3         A3        B3        NaN     NaN
5           4         A4        B4        400    Milk
  Customer_ID Product_ID product First_Name Last_Name
0           1        100     Oil         A1        B1
1           1        200   Sugar         A1        B1
2           1        300     Tea         A1        B1
3           2        NaN     NaN         A2        B2
4           3        NaN     NaN         A3        B3
5           4        400    Milk         A4        B4

## 2.4 Many-to-many merge
A more complicated relationship to manage using merge method is the many-to-many. Consider the example of customers and products. The customer DataFrame contains information about customers, while products has details about differnt grocery items. One customer can buy non or many products, and any product can be purchased by non or many customers. Pandas manage this relationship using merge method. Like SQL's JOIN clause, `pandas.merge` allows two DataFrames to be joined on one or more keys. The function provides a series of parameters (`on`, `left_on`, `right_on`, `left_index`, `right_index`) allowing you to specify the columns or indexes on which to join. In version 0.17.0. Pandas added the argument `indicator`. If True, a Categorical-type column called `_merge` will be added to the output object that takes on values. Here is a simple example.

In [35]:
df1 = pd.DataFrame({'key': ['a', 'a', 'b', 'c', 'a', 'b','c'], 'd1': range(7)})
df2 = pd.DataFrame({'key': ['d', 'd', 'b', 'b', 'b', 'a'], 'd1': range(6)})
print (df1)
print (df2)
merge= pd.merge(df1,df2, how='outer',indicator='True')
print (merge)

  key  d1
0   a   0
1   a   1
2   b   2
3   c   3
4   a   4
5   b   5
6   c   6
  key  d1
0   d   0
1   d   1
2   b   2
3   b   3
4   b   4
5   a   5
   key  d1        True
0    a   0   left_only
1    a   1   left_only
2    a   4   left_only
3    a   5  right_only
4    b   2        both
5    b   3  right_only
6    b   4  right_only
7    b   5   left_only
8    c   3   left_only
9    c   6   left_only
10   d   0  right_only
11   d   1  right_only

In [36]:
print (df1)
print (df2)
merge = pd.merge(df1,df2, how='outer',indicator='True', on='d1')
print (merge)

  key  d1
0   a   0
1   a   1
2   b   2
3   c   3
4   a   4
5   b   5
6   c   6
  key  d1
0   d   0
1   d   1
2   b   2
3   b   3
4   b   4
5   a   5
  key_x  d1 key_y       True
0     a   0     d       both
1     a   1     d       both
2     b   2     b       both
3     c   3     b       both
4     a   4     b       both
5     b   5     a       both
6     c   6   NaN  left_only

In cases that there is a meaningful index in one of the columns, this index can replace the original DataFrame index. By default, set index returns a new DataFrame, so you will have to specify if you would like the changes to occur in place.

## 2.5 Join

Before joining two DataFrames, we need to understand the concept of joining. Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame. Like merge, join also provides a set of parameters (`on`, `how`, `lsuffix`, `rsuffix`, `sort`) to specify the columns or indexes on which to join. The following example demonstrates how to join two DataFrames.

In [37]:
customers_df.set_index('Customer_ID', inplace=True)
shopping_history_df.set_index('Customer_ID', inplace=True)
print (customers_df)
print (shopping_history_df)

            First_Name Last_Name
Customer_ID
1                   A1        B1
2                   A2        B2
3                   A3        B3
4                   A4        B4
            Product_ID product
Customer_ID
1                  100     Oil
1                  200   Sugar
1                  300     Tea
4                  400    Milk
5                  500    Eggs

The DataFrame also has a convenient join method for merging on the index. This is used when you have objects with similar row labels, but different columns.

In [38]:
joined_df = customers_df.join(shopping_history_df,how="outer")
print (customers_df)
print (shopping_history_df)
print (joined_df)

            First_Name Last_Name
Customer_ID
1                   A1        B1
2                   A2        B2
3                   A3        B3
4                   A4        B4
            Product_ID product
Customer_ID
1                  100     Oil
1                  200   Sugar
1                  300     Tea
4                  400    Milk
5                  500    Eggs
            First_Name Last_Name Product_ID product
Customer_ID
1                   A1        B1        100     Oil
1                   A1        B1        200   Sugar
1                   A1        B1        300     Tea
2                   A2        B2        NaN     NaN
3                   A3        B3        NaN     NaN
4                   A4        B4        400    Milk
5                  NaN       NaN        500    Eggs

## 2.5 Combining data with overlap

We use this method when we want to `patch` values in one object from values for matching indices in the other.  Note that this method only takes values from the right DataFrame if they are missing in the left DataFrame. Consider the following example:

In [39]:
import numpy as np
data1 = pd.DataFrame([[1,3,np.nan],[np.nan,10,np.nan],[np.nan,5,3]])
data2 = pd.DataFrame([[10,np.nan,4],[np.nan,5,3],[2,4,np.nan]])
print (data1)
print (data2)
data = data1.combine_first(data2)
print (data)

     0   1    2
0  1.0   3  NaN
1  NaN  10  NaN
2  NaN   5  3.0
      0    1    2
0  10.0  NaN  4.0
1   NaN  5.0  3.0
2   2.0  4.0  NaN
     0     1    2
0  1.0   3.0  4.0
1  NaN  10.0  3.0
2  2.0   5.0  3.0

## 2.6 Data Reshaping:

Hierarchical indexing : `Stack` and `unstack`

Hierarchical indexing provides a more structure way of presenting tabular data. There are two main methods for pivoting data with Hierarchical indexing.

* stack: this rotates or pivots from the columns in the data to the rows
* unstack: this pivots from the rows into the columns

In [40]:
tuples = list(zip(*[['L1_A', 'L1_A', 'L1_B', 'L1_B','L1_C', 'L1_C', 'L1_D', 'L1_D'], ['L2_1', 'L2_2', 'L2_1','L2_2','L2_1', 'L2_2', 'L2_1','L2_2']]))
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
data = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])
print (data)
result = data.stack()
print (result)

                     A         B
first second
L1_A  L2_1   -0.625649 -1.134004
      L2_2    1.359020  0.690455
L1_B  L2_1    0.053271 -0.722650
      L2_2   -0.303441  0.784758
L1_C  L2_1   -0.716713 -1.088034
      L2_2    0.366367 -1.295709
L1_D  L2_1    1.804594  1.583144
      L2_2    0.430146  0.579148
first  second
L1_A   L2_1    A   -0.625649
               B   -1.134004
       L2_2    A    1.359020
               B    0.690455
L1_B   L2_1    A    0.053271
               B   -0.722650
       L2_2    A   -0.303441
               B    0.784758
L1_C   L2_1    A   -0.716713
               B   -1.088034
       L2_2    A    0.366367
               B   -1.295709
L1_D   L2_1    A    1.804594
               B    1.583144
       L2_2    A    0.430146
               B    0.579148
dtype: float64

In [41]:
data.unstack()

               A                   B
second      L2_1      L2_2      L2_1      L2_2
first
L1_A   -0.625649  1.359020 -1.134004  0.690455
L1_B    0.053271 -0.303441 -0.722650  0.784758
L1_C   -0.716713  0.366367 -1.088034 -1.295709
L1_D    1.804594  0.430146  1.583144  0.579148

In [42]:
joined_df = customers_df.join(shopping_history_df, how= 'outer')
print (shopping_history_df)
print (customers_df)
print (joined_df)

            Product_ID product
Customer_ID
1                  100     Oil
1                  200   Sugar
1                  300     Tea
4                  400    Milk
5                  500    Eggs
            First_Name Last_Name
Customer_ID
1                   A1        B1
2                   A2        B2
3                   A3        B3
4                   A4        B4
            First_Name Last_Name Product_ID product
Customer_ID
1                   A1        B1        100     Oil
1                   A1        B1        200   Sugar
1                   A1        B1        300     Tea
2                   A2        B2        NaN     NaN
3                   A3        B3        NaN     NaN
4                   A4        B4        400    Milk
5                  NaN       NaN        500    Eggs

**Exercise:** Try to implement the same code using pivot (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html)

## 2.7 Duplication:

The DataFrame method `duplicated` returns a Boolean Series indicating whether each row is a duplicate or not:

In [43]:
data.duplicated()

first  second
L1_A   L2_1      False
       L2_2      False
L1_B   L2_1      False
       L2_2      False
L1_C   L2_1      False
       L2_2      False
L1_D   L2_1      False
       L2_2      False
dtype: bool

Relatedly, `drop_duplicates` returns a DataFrame where the duplicated array is without duplicated rows.

In [44]:
data = pd.DataFrame({'k1': ['Milk'] * 3 + ['Cheese'] * 4,  'k2': [1, 1, 2, 3, 3, 4, 4]})
print (data)
data.duplicated()
clean_without_duplicates = data.drop_duplicates()
print (clean_without_duplicates)

       k1  k2
0    Milk   1
1    Milk   1
2    Milk   2
3  Cheese   3
4  Cheese   3
5  Cheese   4
6  Cheese   4
       k1  k2
0    Milk   1
2    Milk   2
3  Cheese   3
5  Cheese   4

As you may have noticed, applying `drop_duplicates` on the whole DataFrame considrs all othe columns together. We can alternatively specify which column we want to capture the duplication at.

In [45]:
v1 = data.drop_duplicates(['k1'])
print (v1)
v2 =  data.drop_duplicates(['k2'])
print (v2)

       k1  k2
0    Milk   1
3  Cheese   3
       k1  k2
0    Milk   1
2    Milk   2
3  Cheese   3
5  Cheese   4

## 2.8 Renaming axis indexes:

Pandas enable modifying the current attribute name using map or renaming methods. Example is as follows:

In [46]:
idf = pd.DataFrame(np.arange(12).reshape((3, 4)),
                  index=['nsw', 'vic', 'tasmania'],
                  columns=['day1', 'day2', 'day3', 'day4'])
print (idf)
idf.index.map(str.upper)
idf.rename(index=str.upper, columns=str.upper)

          day1  day2  day3  day4
nsw          0     1     2     3
vic          4     5     6     7
tasmania     8     9    10    11

          DAY1  DAY2  DAY3  DAY4
NSW          0     1     2     3
VIC          4     5     6     7
TASMANIA     8     9    10    11

In [47]:
idf

          day1  day2  day3  day4
nsw          0     1     2     3
vic          4     5     6     7
tasmania     8     9    10    11

Please note `rename` keeps the original value of the data unchanged. To change the original DataFrame, you need to do that in place. You can also `rename` a subset of columns.

In [48]:
idf.rename(index=str.upper, columns=str.upper, inplace=True)
idf

          DAY1  DAY2  DAY3  DAY4
NSW          0     1     2     3
VIC          4     5     6     7
TASMANIA     8     9    10    11

More details and examples can be found in http://pandas.pydata.org/pandas-docs/stable/merging.html and "Python for Data Analysis" book pages 177-193.
https://nikolaygrozev.wordpress.com/2015/07/01/reshaping-in-pandas-pivot-pivot-table-stack-and-unstack-explained-with-pictures/